# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c10ea524894476be7f67c841047a96839edbdf15bdcfdf53b12b3da06812a404512bb688a3f55aebbd29773bbd87de9cf5a435f4253c5745cfd26f19877edd47

test:
  secret_key_base: 096e484980f0fe5727eefbc4fa2f0239a2de8c29f8d66c4abeda23742a0cf4d6f40362e808f03124f8dc458513a122ecf39868fc6440f9f99d8684c788ff9fdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
